# Generated by Django 4.1.1 on 2022-09-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supers',
            new_name='Super',
        ),
    ]
